language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.0

cache:
  directories:
    - node_modules

before_install:
  - brew reinstall node
  - npm install
  - npm install -g react-native-cli
  - gem install cocoapods
  - npm run generate_env

script:
  - react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios
  - react-native bundle --dev false --entry-file index.android.js --bundle-output android/main.jsbundle --platform android
