language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.0

cache:
  directories:
    - node_modules

before_install:
  - brew reinstall node
  - npm install
  - npm install -g react-native-cli
  # - gem install cocoapods
  - npm run generate_env $USER $PASS
  - sudo gem update fastlane

before_script:
  - echo 'Check tests'
  - npm run test

script:
  - echo 'Check if we can generate the bundles'
  - react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios
  - react-native bundle --dev false --entry-file index.android.js --bundle-output android/main.jsbundle --platform android
  - echo 'Check if we can build the ipa and apk'
  - npm run build
