language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator9.0

cache:
  directories:
    - node_modules

before_install:
  - scripts/ci_dependencies.sh

before_script:
  - npm run test
  - npm run lint

script:
  - scripts/ci_bundle.sh
  - npm run build

deploy:
  provider: script
  script: scripts/ci_deploy.sh
  on:
    branch: develop
