fastlane_version '2.13.0'

before_all do
  cocoapods
end

desc 'Submit a new Alpha Build to Apple TestFlight'
lane :alpha do
  gym
  pilot
end

desc 'Submit a new Beta Build to Apple TestFlight'
lane :beta do
  gym
  pilot
end

desc 'Deploy a new version to the App Store'
lane :release do
  gym
  deliver
end

after_all do |lane|

end

error do |lane, exception|

end
