fastlane_version '2.14.2'
require 'json'

# Fastlane always will be called either from '/ios' or '/android'
PATH_ROOT = Dir.pwd.split('/')[0..-3].join('/')
PATH_ANDROID = "#{PATH_ROOT}/android"
PATH_IOS = "#{PATH_ROOT}/ios"

VERSION = ENV['npm_package_version'] || JSON.parse(File.read "#{PATH_ROOT}/package.json")['version']

ICON = '../assets/icon.png'
ICON_WATCH = '../assets/icon.png'
ICON_ALPHA = '../assets/icon_alpha.png'

def mynotification(message)
    notification(title: 'WifiUC', subtitle: PLATFORM, sound: 'Purr', message: message, app_icon: ICON, activate: 'com.apple.terminal', content_image: '')
end

lane :none do
  puts 'Do nothing'
end
