import '../../scripts/Fastfile'

before_all do
  CRASHLYTICS_API_TOKEN = 'd6c5fb7c298d35bbea50ef09cd0d44e1c06d1401'.freeze
  CRASHLYTICS_BUILD_SECRET = 'fad6fff8529401e43667089948e7545d9a7d2a6563fe0ebddfbf00bf3d3105b3'.freeze
end

def upload(track = 'beta')
  mynotification("Uploading... #{track}", 'Uploading')
  supply(
    track: track,
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
  )
end

desc 'Build and sign apk'
lane :build do
  mynotification('Building...', 'Building')
  gradle(
    task: 'assembleRelease',
  )
end

lane :distribute do
  puts 'Doesn\'t do anything'
end

desc 'Runs all the tests'
lane :test do
  gradle(task: 'test')
end

desc 'Submit a new Alpha Build to Crashlytics Beta'
lane :alpha do
  build
  upload('alpha')
  mynotification('Finished uploading alpha version', 'Done')
end

desc 'Submit a new Beta Build to Crashlytics Beta'
lane :beta do
  build
  upload('beta')
  mynotification('Finished uploading beta version', 'Done')
end

desc 'Deploy a new version to the Google Play'
lane :deploy do
  build
  upload('production')
  mynotification('Finished uploading Google Play version', 'Done')
end

desc 'Upload metada and screenshots'
lane :metadata do
  supply(
    skip_upload_apk: true
  )
end

after_all do |lane|
end

error do |lane, exception|
end
